# Generated by Django 3.0.5 on 2020-04-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
    ]
